from abc import ABC, abstractmethod
from typing import Any

class BaseArtifactStore(ABC):
    @abstractmethod
    def put(self, key: str, value: Any) -> None: ...
    @abstractmethod
    def get(self, key: str) -> Any: ...
    @abstractmethod
    def exists(self, key: str) -> bool: ...
    @abstractmethod
    def delete(self, key: str) -> None: ...
    @abstractmethod
    def metadata(self, key: str) -> dict: ...
